### ISSUE TITLE
Feature Request: Helix editor integration

### ISSUE THREAD

**Issue by btvoidx** [onyx-lang/onyx#84]
It should be pretty straightforward to add [Helix](https://helix-editor.com) support. Syntax highlighting is done with tree-sitter queries, which there is a lack of as I understand, but LSP only needs to be properly hooked up.

See [Adding Languages](https://docs.helix-editor.com/guides/adding_languages.html).

**Comment by d2718** [comment]
I think this is probably more of a job for [`helix`](https://github.com/helix-editor/helix) than for here, but if anyone is interested, I managed to get this to work with only minimal frustration.

There is [an MIT-licensed grammar here](https://github.com/elias-michaias/onyx-tree-sitter). Using that, I added the following stanzas to my languages.toml:

```toml
[language-server.onyx-lsp]
command = "onyx"
args = ["lsp"]
required-root-patterns = ["onyx-pkg.kdl", "*.onyx"]

[[language]]
name = "onyx"
scope = "source.onyx"
injection-regex = "onyx"
file-types = ["onyx"]
roots = ["onyx-pkg.kdl"]
comment-token = "//"
indent = { tab-width = 4, unit = "    " }
language-servers = ["onyx-lsp"]

[[grammar]]
name = "onyx"
source = { git = "https://github.com/elias-michaias/onyx-tree-sitter", rev = "dcb69e8030ee5fa5e6e3b3b62bbf6210fb8061c8" }
```

And then asked Helix to fetch and build it

```
$ hx --grammar fetch

$ hx --grammar build
```

The one snag was that I had to manually create the directory `helix/runtime/queries/onyx` and copy the query files from `helix/runtime/sources/onyx/queries` into it.

I'm happy to formally write this up somewhere if that would be helpful.
